### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by xjhzjucas** [kellylab/viral-protein-function-plm#2]
Hi developer:
Thank you for develop such nice tool! I met some basic problems of installation.
First I use 'git clone' successfully download the files into my server, then I followed the instruction successfully bulit the 2 conda envs.
When I run the  command ' bash test.sh' in the path of viral-protein-function-plm, it turned out errors, I don't know what was wrong. 
What's more, I'm not sure which conda env should we activate when we run the test.sh and when we make prediction.
Thank you so much!

**Comment by zachflam** [comment]
Hi, thanks for sharing. If you have the conda envs built you do not need to activate either of them. The activation should be done within the test.sh bash script. 

Can you share the error message you encountered?

**Comment by xjhzjucas** [comment]
> Hi, thanks for sharing. If you have the conda envs built you do not need to activate either of them. The activation should be done within the test.sh bash script.
> 
> Can you share the error message you encountered?

Hi @zachflam ,
the error message was like this:

Traceback (most recent call last):
  File "scripts/embed_faa.py", line 37, in <module>
    main()
  File "scripts/embed_faa.py", line 33, in main
    embedding = protbert_bfd_embed(faa_path=faa_path, max_length=MAX_LENGTH, num_gpus=NUM_GPU, batch_size=BATCH_SIZE)
  File "/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/protbert_bfd_embed_utils.py", line 42, in protbert_bfd_embed
    transformer_bfd = BioTransformers(backend='protbert_bfd', num_gpus=num_gpus)
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/utils/deprecated.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/utils/deprecated.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/bio_transformers.py", line 55, in __new__
    num_gpus=num_gpus,
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/wrappers/transformers_wrappers.py", line 64, in __init__
    model_dir=model_dir, device=device
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/wrappers/rostlab_wrapper.py", line 39, in __init__
    model_dir, do_lower_case=False, padding=True
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1680, in from_pretrained
    user_agent=user_agent,
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/transformers/file_utils.py", line 1337, in cached_path
    local_files_only=local_files_only,
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/transformers/file_utils.py", line 1553, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/predict_function.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
2024-02-02 23:08:09.710140: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Namespace(faa='test/test.faa', out='test_out', efam_calibration_threshold=True, output_embeddings=False, output_predictions=True, prediction_heatmap=True)
Traceback (most recent call last):
  File "/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/predict_function.py", line 72, in <module>
    main()
  File "/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/predict_function.py", line 48, in main
    embedding_dict = pickle.load(open('{0}/{1}_embeddings_dict.pkl' ''.format(out_path, faa_file_name), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/test_out/test_embeddings_dict.pkl'

Can you help me? Thank you so much!

**Comment by xjhzjucas** [comment]
Hi @zachflam 
The error was like this:

Traceback (most recent call last):
  File "scripts/embed_faa.py", line 37, in <module>
    main()
  File "scripts/embed_faa.py", line 33, in main
    embedding = protbert_bfd_embed(faa_path=faa_path, max_length=MAX_LENGTH, num_gpus=NUM_GPU, batch_size=BATCH_SIZE)
  File "/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/protbert_bfd_embed_utils.py", line 42, in protbert_bfd_embed
    transformer_bfd = BioTransformers(backend='protbert_bfd', num_gpus=num_gpus)
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/utils/deprecated.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/utils/deprecated.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/bio_transformers.py", line 55, in __new__
    num_gpus=num_gpus,
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/wrappers/transformers_wrappers.py", line 64, in __init__
    model_dir=model_dir, device=device
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/biotransformers/wrappers/rostlab_wrapper.py", line 39, in __init__
    model_dir, do_lower_case=False, padding=True
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1680, in from_pretrained
    user_agent=user_agent,
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/transformers/file_utils.py", line 1337, in cached_path
    local_files_only=local_files_only,
  File "/mnt/sdb/xjh/miniconda3/envs/plm_vpf_embed/lib/python3.7/site-packages/transformers/file_utils.py", line 1553, in get_from_cache
    "Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/predict_function.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
2024-02-02 23:08:09.710140: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Namespace(faa='test/test.faa', out='test_out', efam_calibration_threshold=True, output_embeddings=False, output_predictions=True, prediction_heatmap=True)
Traceback (most recent call last):
  File "/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/predict_function.py", line 72, in <module>
    main()
  File "/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/scripts/predict_function.py", line 48, in main
    embedding_dict = pickle.load(open('{0}/{1}_embeddings_dict.pkl' ''.format(out_path, faa_file_name), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sdb/xjh/software/plm_vpf/viral-protein-function-plm/test_out/t

**Comment by zachflam** [comment]
> ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

It looks like the machine you ran the code on is not connected to the internet. The function classifier model requires downloading a pretrained language model from huggingface through the biotransformers package.

Were you connected to the internet?

**Comment by xjhzjucas** [comment]
> > ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
> 
> It looks like the machine you ran the code on is not connected to the internet. The function classifier model requires downloading a pretrained language model from huggingface through the biotransformers package.
> 
> Were you connected to the internet?

Hi @zachflam 
Thank you for your help, I did connect to the internet but it also turned out that error. 
Maybe the internet of my server can not connect to that website(requires downloading a pretrained language model from huggingface through the biotransformers package). Can I download what I need here in another method? Like download that into my laptop first and then pass it to the server, can you share the website to me if this method may work?
Thank you so much !

**Comment by zachflam** [comment]
Here is a post from another user in a different issue. https://github.com/kellylab/viral-protein-function-plm/issues/1#issuecomment-1923393708

I would check out that issue where they are dealing with a similar problem. The pretrained language model gets downloaded one time (which can be done manually) and then you can store the model in the default cache path or set the cache path to point to the model.
